### ISSUE TITLE
Can't save records that have " ' " in the title. 

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/Timecontrol#5]
Try saving a record that has "Foto's" in the title. You will get "Sorry! Attempt to access restricted file.
We are looking for this file path: modules//.php
We are looking here:
Real file path: "

coreBOS is the newest version, Timecontrol is updated with new PHP7 files from last commit.

**Comment by Luke1982** [comment]
It seems this issue also appears when the apastrophy is in the 'related to'

**Comment by joebordes** [comment]
I could not reproduce the issue in the title field but I updated the code with the latest vtlib version, eliminated some warnings and fixed this error in the related field where I could reproduce it.

Please update your code and try again.
Let me know how it goes.

Thanks!

**Comment by Luke1982** [comment]
That did the trick!

**Comment by Luke1982** [comment]
Seems the problem still occurs. Whenever I try to create a record related to a TT the same thing occurs. hard to find a common denominator here...

**Comment by joebordes** [comment]
Can you upload a screenshot or video? Maybe that will give me enough to understand what may be the problem.

**Comment by Luke1982** [comment]
[timecontrol_saving_problem.zip](https://github.com/tsolucio/Timecontrol/files/1021562/timecontrol_saving_problem.zip)

**Comment by Luke1982** [comment]
A screencast of what is happening

**Comment by joebordes** [comment]
I think I got it:

https://github.com/tsolucio/Timecontrol/commit/87db1be80f0ebd5d7977fd163189bcf271f02d3a

I found a few other issues also, especially this one:

https://github.com/tsolucio/Timecontrol/commit/4fa1cbfe804106fb7e5f58077a5ce8f17b5105bf

Copy the file modules/Timecontrol/changeSets/fixTimecontrolActionURL.xml into 

```
modules/cbupdater/cbupdates
```

load and apply changesets to get better/correct action links

let me know how it goes

**Comment by joebordes** [comment]
Thanks!!

**Comment by Luke1982** [comment]
Thanks! Will try and let you know.

**Comment by Luke1982** [comment]
Took me long enough, but this seems to do the trick!

**Comment by joebordes** [comment]
:-)
